# Syntax is: <testblock1>:
#              <metric1>:
#                - <parameter1a>: <value>
#                  <parameter1b>: <value>
#                  ..
#                - <parameter2a>: <value>
#                  <parameter2b>: <value>
#                  ..
#                ..
#              <metric2>:
#              ..
#            <test_block2>:
#            ..
#
# where: <testblock1> etc is the name of the testblock referenced in the application.py (e.g. 'atf.start("<testblock1>")')
#        <metric1> etc is the name of a metric defined in the atf_metrics package (view atf_metrics/config/metrics.yaml for the list of available metrics)
#         a metric can receive a list of parameter sets for example if you want to observe the publish_rate of multiple topics
#        <parameter1> etc are parameters defined for the corresponding metric; the parameters groundtruth and groundtruth_epsilon are available for all metrics
#         in case you don't want to pass any parameters:
#            <testblock1>:
#              <metric1>: []
#              <metric2>:
#              ..
#
# The metrics are calculated from the bagfile recorded during the recording step of the test. However if one of your metrics depends on a topic make sure it is recorded by
# adding it to the recorded topics in the robots config. See the raw3-3.yaml for a more detailed description.

testblock_01:
  time: []
  path_length:
    - root_frame: map
      measured_frame: base_link
  #velocity_average:
    #- root_frame: map
      #measured_frame: base_link
  #velocity_max:
    #- root_frame: map
      #measured_frame: base_link
  #velocity_median:
    #- root_frame: map
      #measured_frame: base_link
  #acceleration_average:
    #- root_frame: map
      #measured_frame: base_link
  #acceleration_max:
    #- root_frame: map
      #measured_frame: base_link
  #acceleration_median:
    #- root_frame: map
      #measured_frame: base_link
  #acceleration_average_odom:
    #- odom_topic: /base/odometry_controller/odometry
  #velocity_average_odom:
    #- odom_topic: /base/odometry_controller/odometry
  #velocity_max_odom:
    #- odom_topic: /base/odometry_controller/odometry
  #velocity_median_odom:
    #- odom_topic: /base/odometry_controller/odometry
