additional_parameters:
    "/atf_test/start_pose":
        "position_x": -0.015202
        "position_y": 0.065268
        "orientation_x": 0.000000
        "orientation_y": 0.000000
        "orientation_z": -0.035242
        "orientation_w": 0.999379
    "/atf_test/goals":
        - "position_x": -0.598205
          "position_y": -7.775455
          "orientation_x": 0.000000
          "orientation_y": 0.000000
          "orientation_z": -0.069621
          "orientation_w": 0.997574
        - "position_x": 3.406765
          "position_y": -3.460930
          "orientation_x": 0.000000
          "orientation_y": 0.000000
          "orientation_z": 0.762074
          "orientation_w": 0.647490
        - "position_x": -3.387702
          "position_y": -3.452081
          "orientation_x": 0.000000
          "orientation_y": 0.000000
          "orientation_z": 0.998672
          "orientation_w": -0.051523
additional_arguments:
    "robot_env": ipa-apartment
